In [1]:
# for printing onto a new line
println("hello")

hello


In [5]:
# assigning variables - Julia chooses type for you 
my_answer = 42
typeof(my_answer)


Int64

In [6]:
my_pi = 3.14
typeof(my_pi)

Float64

In [7]:
hi = "hi!"
typeof(hi)

String

In [8]:
hi = 2
typeof(hi)

Int64

In [9]:
#= hioev
vseuiovn
hviousnv =# #for multiline comment 

In [13]:
# exercise 1
days = 365 
days_float = convert(Float64, days)
typeof(days_float)

Float64

In [16]:
# strings 
s1 = "hi"
s2 = """hi""" # can use quotes within this 
# single quotation marks define a character 
# $ to insert existing variables into a string and evaluate expressions within a string
# concatenate string use string() or * 
hihi = string("hi", "hi")
s3 = "fiosn"
s4 = "fueisn"
println(hihi)
println(s3*s4)

hihi
fiosnfueisn


In [15]:
# tuples and arrays contain ordered sequences of elements an dictionaries are not ordered, 
# tuple content cannot be changed

In [17]:
# dictionaries use Dict()
phonebook = Dict("Jenny"=>"87948","hufioes"=>"54839")

Dict{String, String} with 2 entries:
  "Jenny"   => "87948"
  "hufioes" => "54839"

In [18]:
phonebook["fjseio"] = "574965"

"574965"

In [20]:
phonebook

Dict{String, String} with 3 entries:
  "Jenny"   => "87948"
  "hufioes" => "54839"
  "fjseio"  => "574965"

In [21]:
phonebook["Jenny"]

"87948"

In [22]:
pop!(phonebook, "Jenny") # delete dictionary entry

"87948"

In [23]:
phonebook

Dict{String, String} with 2 entries:
  "hufioes" => "54839"
  "fjseio"  => "574965"

In [24]:
# can't index into dictionaries 

In [26]:
# Tuples are made by enclosing elemnts in ()
food = ("apple","pear","milk")
food[2]
# cant reassign


"pear"

In [36]:
# Arrays are both mutable and ordered and made by enclosing elemnts in square brackets 
numbers = [1,2,3,4,5]

5-element Vector{Int64}:
 1
 2
 3
 4
 5

In [37]:
numbers[5]

5

In [38]:
numbers[5] = 10

10

In [39]:
numbers[5]

10

In [40]:
numbers

5-element Vector{Int64}:
  1
  2
  3
  4
 10

In [41]:
# add items to array with push! and remove with pop! 
push!(numbers, 3423)

6-element Vector{Int64}:
    1
    2
    3
    4
   10
 3423

In [42]:
pop!(numbers)

3423

In [43]:
numbers

5-element Vector{Int64}:
  1
  2
  3
  4
 10

In [46]:
# loops - more julian way of nested for loop
m, n = 5, 5
C = [i+j for i in 1:m, j in 1:n] # array comprehension, can also put an array comprehension inside a loop 
# this is the same as doing
A = zeros(m, n)
for i in 1:m # or for i in 1:m, j in 1:n 
    for j in 1:n
        A[i, j] = i + j 
    end
end
A

5×5 Matrix{Float64}:
 2.0  3.0  4.0  5.0   6.0
 3.0  4.0  5.0  6.0   7.0
 4.0  5.0  6.0  7.0   8.0
 5.0  6.0  7.0  8.0   9.0
 6.0  7.0  8.0  9.0  10.0

In [48]:
# conditionals 
x, y = 4, 10
if x > y 
    x
else 
    y 
end

# or instead can use a ternary operator 
(x > y) ? x : y # question if x is bigger than y, if so return x and if not return y 


10

In [52]:
# functions 
function f(x)
    x^2
end 
# OR 
f2(x) = x^2 
# OR anonymous function 
f3 = x -> x^2
# mutating functions have ! after their name

#11 (generic function with 1 method)

In [54]:
# broadcasting defined by a . 
A = [i + 3*j for j in 0:2, i in 1:3]
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [55]:
f.(A)

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81